[project]
name = "Bot_a-Roja-WA_Automation"
version = "0.1.0"
description = "It is what it is"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
    "google-genai>=1.33.0",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
]
